[project]
name = "lambda-data-pipeline-mcp"
version = "1.0.3"
description = "A sovereign, high-speed, local-first Big Data Ingestion, Filtering, and Analytical Pipeline Orchestrator over the Model Context Protocol."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "SEOSiri-Official", email = "info@seosiri.com" }
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Security"
]
dependencies = [
    "mcp>=1.0.0",
    "fastmcp>=0.1.0",
    "requests==2.34.2",
    "fastapi==0.110.0",
    "uvicorn==0.31.1",
    "pydantic==2.13.4",
    "starlette==0.36.3"
]

[project.urls]
Homepage = "https://www.seosiri.com/2026/07/seosiri-mcp-servers.html"
Documentation = "https://www.seosiri.com/2026/07/seosiri-mcp-servers.html"
Repository = "https://github.com/SEOSiri-Official/lambda-data-pipeline-mcp.git"

[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]
